{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.cluster.name }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username }}
  password: {{- if .Values.postgresql.auth.password }}
    {{- .Values.postgresql.auth.password }}
  {{- else }}
    {{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-credentials" .Values.postgresql.cluster.name) }}
    {{- if $secret }}
    {{- index $secret.data "password" | b64dec }}
    {{- else }}
    {{- randAlphaNum 32 }}
    {{- end }}
    {{- end }}
  database: {{ .Values.postgresql.auth.database }}
{{- end }}
